name: Snyk with Gradle

on: 
  push:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: echo "${{ github.workspace }}"

      - name: Use Node.js for installing Snyk
        uses: actions/setup-node@v2
        with:
          node-version: 18.4

      # Install & prepare Snyk
      - run: npm install --location=global snyk

      - name: Setup Snyk
        env:
          SNYK_API: ${{ secrets.SNYK_API }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth "$SNYK_TOKEN"

      - name: Snyk Open Source Scanning
        env:
          SNYK_API: ${{ secrets.SNYK_API }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --org=${{ secrets.SNYK_ORG }} --all-sub-projects
        continue-on-error: true
        
      - name: Snyk Open Source Monitor
        env:
          SNYK_API: ${{ secrets.SNYK_API }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor --org=${{ secrets.SNYK_ORG }} --all-sub-projects
      
